# Generated by Django 3.2.4 on 2021-06-17 20:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20210617_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 17, 20, 13, 4, 893259, tzinfo=utc)),
        ),
    ]
